---
language:   python
python:     3.7

os: osx 
image_osx: xcode10

before_install:
        - sudo apt update

install:
        - pip install ansible


script:
        - ansible-playbook tasks/createFrench.lproj.yml --syntax-check
        - ansible-playbook tasks/createFrench.lproj.yml --connection=local --sudo
