---
language:   python

os: osx 
image_osx: xcode11

before_install:
        - sudo apt update

install:
        - apt install python-pip
        - pip install ansible


script:
        - ansible-playbook tasks/createFrench.lproj.yml --syntax-check
        - ansible-playbook tasks/createFrench.lproj.yml --connection=local --sudo
