---
language:   python
python:     2.7

before_install:
        - sudo apt update

install:
        - pip install ansible


script:
        - ansible-playbook tasks/createFrench.lproj.yml --syntax-check
        - ansible-playbook tasks/createFrench.lproj.yml --connection=local --sudo
