---
language:   python
python:     2.7
services:   ansible

before_install:
        - sudo apt update

install:
        - pip install ansible
        - "printf '[defaults]\nroles_path = ../' > ansible.cfg"


script:
        - ansible-playbook createFrench.lproj.yml -u remoteUser -K --extra-vars "adminUser=RemoteUser" --syntax-check
