---
language:   python

os: osx

image_osx: xcode10.1

before_install:
        - sudo apt update

install:
        - sudo apt install python-pip
        - pip install ansible


script:
        - ansible-playbook tasks/createFrench.lproj.yml --syntax-check
        - ansible-playbook tasks/createFrench.lproj.yml --connection=local --sudo
